

<script src="<?php echo BASE_URL.'public/js/jquery.js' ?>"> </script> 
<script src="<?php echo BASE_URL.'public/js/jquery.tools.min.js' ?>"></script>
<!-- dateinput styling -->
<link href="<?php echo BASE_URL.'public/css/calender.css' ?>" rel="stylesheet">   
 
<!-- HTML5 date input -->
<form action="transactiondetails" method="post">
    <br>
    <div>
       Choose the type of transactions
      <select name="users" onchange="">
          <option value="" selected>Default</option>
          <option value="credit">Credit</option>
          <option value="debit">Debit</option>
        </select>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      </div>
      <div>
      Enter the Dates to get the Transactions information
     
      <input type="date" placeholder="from" name="date_1"/>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <input type="date" placeholder="to" name="date_2"/>
      <br>
       </div>
      <input type="submit" value="submit" name="submit"/>
</form> 
<script>
  $(":date").dateinput();
</script>

<form>
		
</form>


  <br><br>
    <title>Transaction Details</title>
    <link href="<?php echo BASE_URL.'public/css/dt/demo_page.css' ?>" rel="stylesheet">
    <link href="<?php echo BASE_URL.'public/css/dt/demo_table.css' ?>" rel="stylesheet">    


    <script type="text/javascript" language="javascript" src="<?php echo BASE_URL.'public/js/jquery.dataTables.js' ?>"> 
    </script>
    <script type="text/javascript" language="javascript" src="<?php echo BASE_URL.'public/js/jquery.js' ?>"> 
    </script>   
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function() {
        $('#example').dataTable( {
          "fnInitComplete": function () {
            var that = this;
            this.$('td').click( function () {
              that.fnFilter( this.innerHTML );
            } );
          }
        } );
      } );
    </script>
    
</head>

<body>
  
    <table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
            <thead>
                <tr>
                  <th> Id </th>
                  <th> Firstname </th>
                  <th> Account Id </th>
                  <th> Amount </th>
                  <th> Current Balance</th>
                  <th> Type </th>
                  <th> status </th>
                  <th> created_at </th>
                  <th> updated_at </th>
                  <br>
                </tr>
            </thead>
              <tbody>
                <?php
                  foreach ($this->data as $val) 
                    { 
                      echo "<tr class=gradeA>";
                      echo "<td align='center'>".$val['id']."</td>"; 
                      echo "<td align='center'>".$val['firstname']."</td>"; 
                      echo "<td align='center'>".$val['account_id']."</td>"; 
                      echo "<td align='center'>".$val['amount']."</td>"; 
                      echo "<td align='center'>".$val['current_balance']."</td>"; 
                      echo "<td align='center'>".$val['type']."</td>"; 
                      echo "<td align='center'>".$val['status']."</td>"; 
                      echo "<td align='center'>".$val['created_at']."</td>"; 
                      echo "<td align='center'>".$val['updated_at']."</td>";              
                      echo "</tr>"; 
                    }       
                  ?>
              </tbody>
      </table>      
  
  </body>
</html>